url: "https://compliancepack.net/"

compress_html:
  comments: ["<!-- ", " -->"]
  blanklines: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

sass:
  sass_dir: css
  sourcemap: never
  style: compressed
