name: Deploy Website

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSH }}
        # install bundle, build jekyll, relaunch website
        script: |
          cd /var/www/html/compliancepack.net
          git stash
          git pull
          npm install
          npm run ji
          npm run jb
          pm2 restart "WEBSITE"

          cd /var/www/html/webapp.faithfulpack.net
          git stash
          git pull
          npm install
          pm2 restart "APP"
    - name: Purge Cloudflare cache
      run: curl https://api.compliancepack.net/v1/purge/${{ secrets.PURGE_PASSWORD }}
